language: python
python:
  - "3.6"
services:
  - mysql
env:
  -DJANGO=2.1.4 DB=mysql
install:
  - pip install -r requirements.txt
before_script: 
  - mysql -e 'create database test;' -u root
script: 
  - python manage.py migrate
  - python manage.py test

notifications:
  email:
    - acekun141@gmail.com
    - loitd@vnptepay.com.vn