# Generated by Django 2.1.4 on 2019-01-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=100)),
                ('require', models.CharField(max_length=100)),
                ('describe', models.TextField(max_length=5000)),
                ('salary', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Info')),
            ],
        ),
    ]
