# Generated by Django 2.1.4 on 2019-01-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_infomationenterprise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfomationEnterprise',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
