# Generated by Django 2.1.4 on 2019-01-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_infomationenterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=200)),
                ('workplace', models.CharField(choices=[('1', 'Hà Nội')], max_length=1)),
                ('amount', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('worktime', models.CharField(choices=[('1', 'Toàn thời gian'), ('1', 'Bán thời gian'), ('1', 'Thực tập')], max_length=1)),
                ('sex', models.CharField(choices=[('1', 'Nam'), ('2', 'Nữ')], max_length=1)),
                ('exp', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('des_of_company', models.TextField(max_length=255)),
                ('describe', models.TextField()),
                ('require', models.TextField()),
                ('skill', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.InfomationEnterprise')),
            ],
        ),
    ]
