# Generated by Django 2.1.4 on 2019-01-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='benefit',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='workplace',
            field=models.CharField(choices=[('1', 'Hà Nội'), ('2', 'Hồ Chí Minh'), ('3', 'Bình Dương'), ('4', 'Bắc Ninh'), ('5', 'Đồng Nai'), ('6', 'Hưng Yên'), ('7', 'Hải Dương'), ('8', 'Đà Nẵng'), ('9', 'Hải Phòng')], max_length=1),
        ),
    ]
