# Generated by Django 2.1.4 on 2019-01-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190124_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomationenterprise',
            name='select',
            field=models.CharField(choices=[('Dưới 10 nhân viên', 'Dưới 10 nhân viên'), ('Từ 10-49 nhân viên', 'Từ 10-49 nhân viên'), ('Từ 50-99 nhân viên', 'Từ 50-99 nhân viên'), ('Từ 100-499 nhân viên', 'Từ 100-499 nhân viên'), ('Từ 500-1000 nhân viên', 'Từ 500-1000 nhân viên'), ('Trên 1000 nhân viên', 'Trên 1000 nhân viên')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='sex',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Nam/Nữ', 'Nam/Nữ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='workplace',
            field=models.CharField(choices=[('Hà Nội', 'Hà Nội'), ('Hồ Chí Minh', 'Hồ Chí Minh'), ('Bình Dương', 'Bình Dương'), ('Bắc Ninh', 'Bắc Ninh'), ('Đồng Nai', 'Đồng Nai'), ('Hưng Yên', 'Hưng Yên'), ('Hải Dương', 'Hải Dương'), ('Đà Nẵng', 'Đà Nẵng'), ('Hải Phòng', 'Hải Phòng')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='worktime',
            field=models.CharField(choices=[('Toàn thời gian', 'Toàn thời gian'), ('Bán thời gian', 'Bán thời gian'), ('Thực tập', 'Thực tập')], max_length=1),
        ),
    ]
