# Generated by Django 2.1.4 on 2019-01-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190127_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='des_of_company',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='describe',
            field=models.TextField(),
        ),
    ]
